version: 2

sources:
  - name: adventureworks_projeto
    description: This is the adventureworks erp postgres database replica
    tables:

      - name: address
        description: |
          One record per address.
        columns:
          - name: addressId
            description: Primary key of the address table
            tests:
              - unique
              - not_null
          - name: city
            description: Name of the city where the address belongs
      
      - name: countryregion
        columns:
          - name: countryregioncode
            description: Primary key of the countryregion table
            tests:
              - unique
              - not_null

      - name: creditcard
        columns:
          - name: creditcardid
            description: Primary key of the credit card table
            tests:
              - unique
              - not_null

      - name: customer
        columns:
          - name: customerid
            description: Primary key of the customer table
            tests:
              - unique
              - not_null 

      - name: person
        columns:
          - name: businessentityid
            description: Primary key of the person table
            tests:
              - unique
              - not_null 

      - name: product
        columns:
          - name: productId
            description: Primary key of the product table
            tests:
              - unique
              - not_null

      - name: salesorderdetail
        columns:
          - name: SalesOrderDetailID
            description: Primary key of the SalesOrderDetail table
            tests:
              - unique
              - not_null

      - name: salesorderheader
        columns:
          - name: SalesOrderID
            description: Primary key of the salesorderheader table
            tests:
              - unique
              - not_null  

      - name: salesorderheadersalesreason
        columns:
          - name: salesreasonid
            description: Field that is part of primary key of the salesorderheadersalesreason table
            tests:
              - not_null
          - name: SalesOrderID
            description: Field that is part of primary key of the salesorderheadersalesreason table
            tests:
              - not_null              

      - name: salesreason
        columns:
          - name: salesreasonid
            description: Field that is part of primary key of the salesreason table
            tests:
              - unique
              - not_null

      - name: stateprovince
        columns:
          - name: stateprovinceid
            description: Primary key of the stateprovince table
            tests:
              - unique
              - not_null      